name: Build
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          sudo bash build.sh ${{ env.BASE_OS_URL }} ${{ secrets.TEST_TOKEN }} ${{ env.TEST_SERVER_ADDRESS }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BRANCH_NAME }}
          path: |
            Roobi.img