name: Build
on:
  workflow_dispatch:
  push:

permissions:
  contents: write


jobs:
  build:
    environment: PS006
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build
        run: |
          sudo bash build.sh ${{ vars.BASE_OS_URL }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.BRANCH_NAME }}
          path: |
            Roobi.img.xz
      - name: make flasher
        run: sudo bash make_flasher.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.BRANCH_NAME }}_flasher
          path: |
            ${{ vars.BRANCH_NAME }}_flasher.img.xz
